language: go

go:
  - 1.7.x
  - 1.8.x

go_import_path: github.com/cloudflare/unsee

# nodejs is needed so that we can install jshint
addons:
  apt:
    packages:
      - nodejs

# install jshint, it's used for linting js files (needs nodejs)
before_script:
  - npm install jshint

script:
  - make test
