language: go

go:
  - 1.7.x
  - 1.8.x

go_import_path: github.com/cloudflare/unsee

# install jshint & eslint, it's used for linting js files (needs nodejs)
before_script:
  - nvm install 6
  - npm install jshint
  - npm install eslint

script:
  - make test
