language: go

go:
  - 1.8.x

go_import_path: github.com/cloudflare/unsee

cache:
  directories:
    - node_modules
    - vendor

env:
  - NODE_ENV=test

before_script:
  - nvm install 8

script:
  - make test
